%% runDemo
% SIH26038_DR - Diabetic Retinopathy Screening Demo
%
% Demonstration interface for:
%   - DR severity prediction
%   - Confidence score
%   - Referable DR screening
%   - Grad-CAM explainability
%
% Project: SIH26038_DR

clear;
clc;
close all;

%% ============================================================
% 1. Find project root
% =============================================================

codeFolder = fileparts(mfilename("fullpath"));
projectRoot = fileparts(codeFolder);

%% ============================================================
% 2. Load trained model
% =============================================================

modelPath = fullfile( ...
    projectRoot, ...
    "models", ...
    "efficientnetb0_DR_trained.mat");

if ~isfile(modelPath)

    error( ...
        "Trained model not found:\n%s", ...
        modelPath);

end

fprintf("Loading trained EfficientNet-B0...\n");

load( ...
    modelPath, ...
    "net", ...
    "classNames");

fprintf("Model loaded successfully.\n");

%% ============================================================
% 3. Create main application window
% =============================================================

fig = uifigure( ...
    "Name", ...
    "SIH26038_DR - Diabetic Retinopathy Screening", ...
    "Position", ...
    [100 100 1200 720]);

%% ============================================================
% 4. Application title
% =============================================================

titleLabel = uilabel( ...
    fig, ...
    "Text", ...
    "AI-Assisted Diabetic Retinopathy Screening", ...
    "Position", ...
    [30 670 1140 35], ...
    "FontSize", ...
    24, ...
    "FontWeight", ...
    "bold", ...
    "HorizontalAlignment", ...
    "center");

subtitleLabel = uilabel( ...
    fig, ...
    "Text", ...
    "EfficientNet-B0 + Grad-CAM", ...
    "Position", ...
    [30 640 1140 25], ...
    "FontSize", ...
    14, ...
    "HorizontalAlignment", ...
    "center");

%% ============================================================
% 5. Image display axes
% =============================================================

originalAxes = uiaxes( ...
    fig, ...
    "Position", ...
    [40 300 500 310]);

title( ...
    originalAxes, ...
    "Original Fundus Image");

originalAxes.XTick = [];
originalAxes.YTick = [];

%% ============================================================
% 6. Grad-CAM axes
% =============================================================

camAxes = uiaxes( ...
    fig, ...
    "Position", ...
    [660 300 500 310]);

title( ...
    camAxes, ...
    "Grad-CAM Explanation");

camAxes.XTick = [];
camAxes.YTick = [];

%% ============================================================
% 7. Prediction result panel
% =============================================================

resultPanel = uipanel( ...
    fig, ...
    "Title", ...
    "Prediction Result", ...
    "Position", ...
    [40 35 1120 190]);

%% ============================================================
% 8. Severity label
% =============================================================

severityLabel = uilabel( ...
    resultPanel, ...
    "Text", ...
    "Severity: --", ...
    "Position", ...
    [30 110 330 35], ...
    "FontSize", ...
    18, ...
    "FontWeight", ...
    "bold");

%% ============================================================
% 9. Confidence label
% =============================================================

confidenceLabel = uilabel( ...
    resultPanel, ...
    "Text", ...
    "Confidence: --", ...
    "Position", ...
    [400 110 300 35], ...
    "FontSize", ...
    18);

%% ============================================================
% 10. Screening label
% =============================================================

screeningLabel = uilabel( ...
    resultPanel, ...
    "Text", ...
    "Screening: --", ...
    "Position", ...
    [750 110 330 35], ...
    "FontSize", ...
    18, ...
    "FontWeight", ...
    "bold");

%% ============================================================
% 11. Status label
% =============================================================

statusLabel = uilabel( ...
    resultPanel, ...
    "Text", ...
    "Select a retinal fundus image to begin.", ...
    "Position", ...
    [30 55 1050 30], ...
    "FontSize", ...
    14, ...
    "HorizontalAlignment", ...
    "center");

%% ============================================================
% 12. Select image button
% =============================================================

selectButton = uibutton( ...
    fig, ...
    "push", ...
    "Text", ...
    "Select Fundus Image", ...
    "Position", ...
    [450 245 300 45], ...
    "FontSize", ...
    16, ...
    "FontWeight", ...
    "bold");

%% ============================================================
% 13. Disclaimer
% =============================================================

disclaimerLabel = uilabel( ...
    fig, ...
    "Text", ...
    "Prototype for research and demonstration; not a clinical diagnosis.", ...
    "Position", ...
    [30 5 1140 20], ...
    "FontSize", ...
    11, ...
    "FontAngle", ...
    "italic", ...
    "HorizontalAlignment", ...
    "center");

%% ============================================================
% 14. Connect button callback
% =============================================================

selectButton.ButtonPushedFcn = ...
    @(src,event) selectFundusImage( ...
        fig, ...
        net, ...
        classNames, ...
        originalAxes, ...
        camAxes, ...
        severityLabel, ...
        confidenceLabel, ...
        screeningLabel, ...
        statusLabel);

%% ============================================================
% 15. Image selection callback
% =============================================================

function selectFundusImage( ...
    fig, ...
    net, ...
    classNames, ...
    originalAxes, ...
    camAxes, ...
    severityLabel, ...
    confidenceLabel, ...
    screeningLabel, ...
    statusLabel)

    %% Select image

    [fileName,filePath] = uigetfile( ...
        { ...
        "*.png;*.jpg;*.jpeg;*.tif;*.tiff", ...
        "Fundus Images"; ...
        "*.*", ...
        "All Files" ...
        }, ...
        "Select Retinal Fundus Image");

    if isequal(fileName,0)

        statusLabel.Text = ...
            "No image selected.";

        return;

    end

    %% Full image path

    imagePath = fullfile( ...
        filePath, ...
        fileName);

    %% Update status

    statusLabel.Text = ...
        "Processing image...";

    drawnow;

    try

        %% ====================================================
        % Read image
        % ====================================================

        originalImage = imread(imagePath);

        %% Ensure RGB

        if ndims(originalImage) == 2

            originalImage = cat( ...
                3, ...
                originalImage, ...
                originalImage, ...
                originalImage);

        end

        if size(originalImage,3) ~= 3

            error( ...
                "The selected image must be grayscale or RGB.");

        end

        %% ====================================================
        % Display original image
        % ====================================================

        imshow( ...
            originalImage, ...
            "Parent", ...
            originalAxes);

        title( ...
            originalAxes, ...
            "Original Fundus Image");

        %% ====================================================
        % Prepare network input
        % ====================================================

        inputSize = net.Layers(1).InputSize;

        networkImage = imresize( ...
            originalImage, ...
            inputSize(1:2));

        %% ====================================================
        % Prediction
        % ====================================================

        scores = predict( ...
            net, ...
            single(networkImage));

        %% Convert scores if necessary

        if isa(scores,"dlarray")

            scores = extractdata(scores);

        end

        scores = squeeze(scores);

        %% ====================================================
        % Find predicted class
        % ====================================================

        [confidence,predictedIndex] = ...
            max(scores);

        predictedClass = ...
            string(classNames(predictedIndex));

        confidencePercent = ...
            double(confidence) * 100;

        %% ====================================================
        % Determine screening category
        % ====================================================

        if ismember( ...
                predictedClass, ...
                ["Level0","Level1"])

            screeningResult = ...
                "Non-referable DR";

        else

            screeningResult = ...
                "Referable DR";

        end

        %% ====================================================
        % Update result labels
        % ====================================================

        severityLabel.Text = ...
            "Severity: " + predictedClass;

        confidenceLabel.Text = ...
            sprintf( ...
            "Confidence: %.2f%%", ...
            confidencePercent);

        screeningLabel.Text = ...
            "Screening: " + screeningResult;

        statusLabel.Text = ...
            "Prediction completed successfully.";

        drawnow;

        %% ====================================================
        % Grad-CAM
        % ====================================================

        statusLabel.Text = ...
            "Generating Grad-CAM...";

        drawnow;

        scoreMap = gradCAM( ...
            net, ...
            networkImage, ...
            predictedIndex, ...
            ReductionLayer="Softmax");

        %% Normalize heatmap

        scoreMap = rescale(scoreMap);

        %% ====================================================
        % Display Grad-CAM overlay
        % ====================================================

        imshow( ...
            networkImage, ...
            "Parent", ...
            camAxes);

        hold( ...
            camAxes, ...
            "on");

        heatmapImage = imagesc( ...
            camAxes, ...
            scoreMap);

        heatmapImage.AlphaData = 0.45;

        axis( ...
            camAxes, ...
            "image");

        camAxes.XTick = [];
        camAxes.YTick = [];

        colormap( ...
            camAxes, ...
            "turbo");

        title( ...
            camAxes, ...
            "Grad-CAM: " + ...
            predictedClass);

        hold( ...
            camAxes, ...
            "off");

        %% ====================================================
        % Console output
        % ====================================================

        fprintf("\n");
        fprintf("============================================\n");
        fprintf("SIH26038_DR PREDICTION\n");
        fprintf("============================================\n");
        fprintf("Image:       %s\n",fileName);
        fprintf("Severity:    %s\n",predictedClass);
        fprintf("Confidence:  %.2f%%\n",confidencePercent);
        fprintf("Screening:   %s\n",screeningResult);
        fprintf("============================================\n");

        %% ====================================================
        % Final status
        % ====================================================

        statusLabel.Text = ...
            "Analysis completed. Grad-CAM shows regions influencing the prediction.";

    catch ME

        %% ====================================================
        % Error handling
        % ====================================================

        statusLabel.Text = ...
            "Error while processing the image.";

        uialert( ...
            fig, ...
            ME.message, ...
            "Prediction Error");

    end

end